### ISSUE TITLE
/auc bankhand spams console and does not work.

### ISSUE THREAD

**Issue by FrozenBeard** [StarTux/CraftBay#9]
I downloaded 2.21 as im not on 1.13 yet to test this plugin, I pulled a custom named item from my echest to test this on and id /auc bankhand and it did nothing in game and spammed the console. 
Thought I would try it as im looking for a plugin to auction off a bunch of custom named items, with custom lores too.
https://pastebin.com/Pzj8hMsp

**Comment by StarTux** [comment]
Hello,
CraftBay 2.21 will only work on Spigot 1.13 or above; not on previous versions. Older Spigot versions don't have some of the methods it calls, which is why you're getting this error:
`Caused by: java.lang.NoSuchMethodError: org.bukkit.enchantments.Enchantment.getKey()Lorg/bukkit/NamespacedKey;`

For use on Spigot 1.12 or below, use CraftBay 2.1 or below, which you can find here: https://dev.bukkit.org/projects/craftbay/files
